#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="docs/autodl_5090_handoff_manifest.md"
TMP_FILE="$(mktemp)"
trap 'rm -f "$TMP_FILE"' EXIT

add_if_exists() {
  local path="$1"
  if [ -f "$path" ]; then
    printf '%s\n' "$path" >> "$TMP_FILE"
  fi
}

add_dir_files() {
  local dir="$1"
  if [ -d "$dir" ]; then
    find "$dir" -type f \
      ! -path '*/__pycache__/*' \
      ! -name '*.pyc' \
      | sort >> "$TMP_FILE"
  fi
}

add_if_exists "README.md"
add_if_exists ".gitignore"
add_if_exists "requirements.txt"
add_dir_files "configs"
add_dir_files "src"
add_dir_files "scripts"
add_dir_files "docs"

add_if_exists "data/debug/README.md"
if [ -d "data/debug" ]; then
  find data/debug -maxdepth 1 -type f \( -name '*.jsonl' -o -name '*.json' -o -name '*.md' \) | sort >> "$TMP_FILE"
fi
if [ -d "data/debug/plots" ]; then
  find data/debug/plots -type f | sort >> "$TMP_FILE"
fi

sort -u "$TMP_FILE" -o "$TMP_FILE"

TOTAL_FILES="$(wc -l < "$TMP_FILE" | tr -d ' ')"
TOTAL_BYTES="$(python3 - "$TMP_FILE" <<'PY'
import os
import sys
total = 0
with open(sys.argv[1], encoding="utf-8") as f:
    for line in f:
        path = line.strip()
        if path and os.path.isfile(path):
            total += os.path.getsize(path)
print(total)
PY
)"

{
  echo "# AutoDL 5090 Handoff Manifest"
  echo
  echo "Generated by:"
  echo
  echo '```bash'
  echo "bash scripts/package_handoff_preview.sh"
  echo '```'
  echo
  echo "## Summary"
  echo
  echo "- Files listed: \`$TOTAL_FILES\`"
  echo "- Total lightweight payload bytes: \`$TOTAL_BYTES\`"
  echo "- This is a preview manifest only; it does not copy raw data or model weights."
  echo
  echo "## Excluded Heavy Paths"
  echo
  echo "- \`.venv/\`"
  echo "- \`external/\`"
  echo "- \`data/raw/\`"
  echo "- \`data/processed/\`"
  echo "- \`logs/\`"
  echo "- \`work/\`"
  echo "- \`tools/\`"
  echo "- model/checkpoint files such as \`*.safetensors\`, \`*.bin\`, \`*.pt\`, \`*.pth\`, \`*.ckpt\`"
  echo
  echo "## Included Files"
  echo
  while IFS= read -r path; do
    size="$(stat -c %s "$path")"
    echo "- \`$path\` (${size} bytes)"
  done < "$TMP_FILE"
  echo
  echo "## Status"
  echo
  echo "- \`HANDOFF_PREVIEW_PASS\`"
  echo "- \`NOT_TRAINING_READY\`"
} > "$OUT"

echo "HANDOFF_PREVIEW_PASS: wrote $OUT"
echo "Files: $TOTAL_FILES"
echo "Bytes: $TOTAL_BYTES"
